/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kieran Bingham, Cameron Sokalski, Jacob Laross
 */

import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.DefaultComboBoxModel;

public class CuttingGUI extends javax.swing.JFrame {
    
    FileReader reader = new FileReader(); 

    DrillDiameter drill = new DrillDiameter(); 
    DrillDiameter spindleDrill = new DrillDiameter();
    /**
     * Creates new form CuttingGUI
     */
    public CuttingGUI() {
        initComponents();
        reader.initialFileReader();
        DefaultComboBoxModel materialListModel = (DefaultComboBoxModel) materialBox.getModel();
        DefaultComboBoxModel diameterListModel = (DefaultComboBoxModel) diameterBox.getModel();
        DefaultComboBoxModel spindleMaterialModel = (DefaultComboBoxModel) spindleMaterialBox.getModel();
        DefaultComboBoxModel spindleDiameterListModel = (DefaultComboBoxModel) diameterBox1.getModel();
        String[] materialNames={"steel","mild steel","carbon steel","stainless steel","bronze","aluminum","brass","plastic","wood"};
        String[] spindleMaterialNames={"Aluminum","Brass","Plastic", "Lexan", "Low Carbon Steel","Medium Carbon Steel","Alloy Steel"};
        for (String name:materialNames){
            materialListModel.addElement(name);
        }
        for (String name:reader.bitFraction){
            diameterListModel.addElement(name); 
        }
        resultLabel.setText(" "); 
        
        for (String name:spindleMaterialNames){
            spindleMaterialModel.addElement(name);
        }
        for (String name:reader.bitFraction){
            spindleDiameterListModel.addElement(name); 
        }
        spindleResultLabel.setText(" ");
        
        diameterBox.setSelectedIndex(15);
        diameterBox1.setSelectedIndex(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        RPMButton = new javax.swing.JButton();
        feedRateButton = new javax.swing.JButton();
        spindleSpeedButton = new javax.swing.JButton();
        mainTitleLabel = new javax.swing.JLabel();
        creditButton = new javax.swing.JButton();
        RPMPanel = new javax.swing.JPanel();
        toolbarPanel = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        RPMMenuButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButton1 = new javax.swing.JButton();
        rpmLabel = new javax.swing.JLabel();
        materialBox = new javax.swing.JComboBox();
        numeratorLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        diameterBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        creditPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        kieranLabel = new javax.swing.JLabel();
        jacobLabel = new javax.swing.JLabel();
        cameronLabel = new javax.swing.JLabel();
        kieranSeparator = new javax.swing.JSeparator();
        jacobSeparator = new javax.swing.JSeparator();
        cameronSeparator = new javax.swing.JSeparator();
        kieranDescription = new javax.swing.JLabel();
        jacobDescription = new javax.swing.JLabel();
        cameronDescription = new javax.swing.JLabel();
        toolbar1 = new javax.swing.JToolBar();
        ravenEyes = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        homeButton = new javax.swing.JButton();
        cat = new javax.swing.JLabel();
        CNCPanel = new javax.swing.JPanel();
        toolbarPanel1 = new javax.swing.JPanel();
        toolbar2 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        spindleMenuButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        spindlePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        diameterBox1 = new javax.swing.JComboBox();
        spindleMaterialBox = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        spindleCalculateButton = new javax.swing.JButton();
        spindleResultLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("hello");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setResizable(false);

        cardPanel.setBackground(new java.awt.Color(102, 0, 102));
        cardPanel.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(102, 0, 102));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        RPMButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        RPMButton.setText("RPM");
        RPMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPMButtonActionPerformed(evt);
            }
        });

        feedRateButton.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        feedRateButton.setText("Feed Rate");
        feedRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedRateButtonActionPerformed(evt);
            }
        });

        spindleSpeedButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spindleSpeedButton.setText("Spindle Speed");
        spindleSpeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spindleSpeedButtonActionPerformed(evt);
            }
        });

        mainTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        mainTitleLabel.setForeground(new java.awt.Color(204, 204, 204));
        mainTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resorces/small_logo.png"))); // NOI18N
        mainTitleLabel.setText("TEJ App");

        creditButton.setText("Credits");
        creditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(mainTitleLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(RPMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(feedRateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spindleSpeedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(creditButton)
                        .addGap(249, 249, 249))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainTitleLabel)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(spindleSpeedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(feedRateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(RPMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85)
                .addComponent(creditButton)
                .addContainerGap())
        );

        cardPanel.add(mainPanel, "menuCard");

        RPMPanel.setBackground(new java.awt.Color(102, 0, 102));

        toolbar.setBackground(new java.awt.Color(153, 153, 153));
        toolbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setMaximumSize(new java.awt.Dimension(186, 25));
        toolbar.setMinimumSize(new java.awt.Dimension(186, 25));
        toolbar.setPreferredSize(new java.awt.Dimension(592, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resorces/ldhssRaven.png"))); // NOI18N
        toolbar.add(jLabel1);

        RPMMenuButton.setText("Main Menu");
        RPMMenuButton.setFocusable(false);
        RPMMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RPMMenuButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RPMMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPMMenuButtonActionPerformed(evt);
            }
        });
        toolbar.add(RPMMenuButton);
        toolbar.add(filler2);

        jButton1.setText("Credits");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        toolbar.add(jButton1);

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rpmLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rpmLabel.setForeground(new java.awt.Color(204, 204, 204));
        rpmLabel.setText("RPM =");

        numeratorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numeratorLabel.setForeground(new java.awt.Color(204, 204, 204));
        numeratorLabel.setText("*              4");

        diameterBox.setEditable(true);
        diameterBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton2.setText("GO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(204, 204, 204));
        resultLabel.setText("= result");

        javax.swing.GroupLayout RPMPanelLayout = new javax.swing.GroupLayout(RPMPanel);
        RPMPanel.setLayout(RPMPanelLayout);
        RPMPanelLayout.setHorizontalGroup(
            RPMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RPMPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(RPMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPMPanelLayout.createSequentialGroup()
                        .addComponent(rpmLabel)
                        .addGap(18, 18, 18)
                        .addGroup(RPMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RPMPanelLayout.createSequentialGroup()
                                .addComponent(materialBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numeratorLabel))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPMPanelLayout.createSequentialGroup()
                        .addComponent(diameterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addComponent(jButton2)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPMPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RPMPanelLayout.setVerticalGroup(
            RPMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPMPanelLayout.createSequentialGroup()
                .addComponent(toolbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(RPMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rpmLabel)
                    .addGroup(RPMPanelLayout.createSequentialGroup()
                        .addGroup(RPMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(materialBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeratorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diameterBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(resultLabel)
                .addGap(205, 205, 205))
        );

        rpmLabel.getAccessibleContext().setAccessibleDescription("");

        cardPanel.add(RPMPanel, "RPMCard");

        header.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(102, 0, 204));
        header.setText("Software Developpment Team");

        footer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        footer.setForeground(new java.awt.Color(102, 0, 204));
        footer.setText("Cutting Speed App V1.2");

        kieranLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kieranLabel.setText("Kieran Bingham");

        jacobLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jacobLabel.setText("Jacob Larose");

        cameronLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cameronLabel.setText("Cameron Sokalski");

        kieranDescription.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        kieranDescription.setForeground(new java.awt.Color(102, 0, 204));
        kieranDescription.setText("Software Design and President");

        jacobDescription.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jacobDescription.setForeground(new java.awt.Color(102, 0, 204));
        jacobDescription.setText("Database Management and COO");

        cameronDescription.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cameronDescription.setForeground(new java.awt.Color(102, 0, 204));
        cameronDescription.setText("Grahpic Design, GUI Developpment and CEO");

        toolbar1.setBackground(new java.awt.Color(153, 153, 153));
        toolbar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbar1.setFloatable(false);
        toolbar1.setRollover(true);
        toolbar1.setMaximumSize(new java.awt.Dimension(186, 25));
        toolbar1.setMinimumSize(new java.awt.Dimension(186, 25));
        toolbar1.setPreferredSize(new java.awt.Dimension(592, 25));

        ravenEyes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resorces/ldhssRaven.png"))); // NOI18N
        toolbar1.add(ravenEyes);

        jButton3.setText("Main Menu");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        toolbar1.add(jButton3);
        toolbar1.add(filler1);

        homeButton.setText("RPM Calc");
        homeButton.setFocusable(false);
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        toolbar1.add(homeButton);

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resorces/cat-small.png"))); // NOI18N

        javax.swing.GroupLayout creditPanelLayout = new javax.swing.GroupLayout(creditPanel);
        creditPanel.setLayout(creditPanelLayout);
        creditPanelLayout.setHorizontalGroup(
            creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jacobLabel)
                            .addComponent(kieranLabel)
                            .addComponent(cameronLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jacobSeparator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(kieranSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cameronSeparator))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jacobDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cameronDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kieranDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(creditPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(header)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(footer))
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(cat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        creditPanelLayout.setVerticalGroup(
            creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addComponent(toolbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(header)
                .addGap(52, 52, 52)
                .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kieranLabel)
                    .addGroup(creditPanelLayout.createSequentialGroup()
                        .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kieranDescription)
                            .addComponent(kieranSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditPanelLayout.createSequentialGroup()
                        .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(creditPanelLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jacobLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jacobDescription)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jacobSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cameronLabel)
                            .addComponent(cameronDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cameronSeparator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cat)
                .addGap(90, 90, 90)
                .addComponent(footer))
        );

        cardPanel.add(creditPanel, "creditPanel");

        CNCPanel.setBackground(new java.awt.Color(102, 0, 102));

        toolbar2.setBackground(new java.awt.Color(153, 153, 153));
        toolbar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbar2.setFloatable(false);
        toolbar2.setRollover(true);
        toolbar2.setMaximumSize(new java.awt.Dimension(186, 25));
        toolbar2.setMinimumSize(new java.awt.Dimension(186, 25));
        toolbar2.setPreferredSize(new java.awt.Dimension(592, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resorces/ldhssRaven.png"))); // NOI18N
        toolbar2.add(jLabel4);

        spindleMenuButton.setText("Main Menu");
        spindleMenuButton.setFocusable(false);
        spindleMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        spindleMenuButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        spindleMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spindleMenuButtonActionPerformed(evt);
            }
        });
        toolbar2.add(spindleMenuButton);
        toolbar2.add(filler3);

        jButton6.setText("Credits");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        toolbar2.add(jButton6);

        javax.swing.GroupLayout toolbarPanel1Layout = new javax.swing.GroupLayout(toolbarPanel1);
        toolbarPanel1.setLayout(toolbarPanel1Layout);
        toolbarPanel1Layout.setHorizontalGroup(
            toolbarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        toolbarPanel1Layout.setVerticalGroup(
            toolbarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(toolbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        spindlePanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><u>Find spinndle speed (RPM) for CNC machines");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("RPM = ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("* 12");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("* Pi");

        diameterBox1.setEditable(true);
        diameterBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        spindleMaterialBox.setModel(new javax.swing.DefaultComboBoxModel());

        spindleCalculateButton.setText("Calculate");
        spindleCalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spindleCalculateButtonActionPerformed(evt);
            }
        });

        spindleResultLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        spindleResultLabel.setForeground(new java.awt.Color(204, 204, 204));
        spindleResultLabel.setText("RPM = ");

        javax.swing.GroupLayout spindlePanelLayout = new javax.swing.GroupLayout(spindlePanel);
        spindlePanel.setLayout(spindlePanelLayout);
        spindlePanelLayout.setHorizontalGroup(
            spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spindlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spindleCalculateButton)
                .addGap(225, 225, 225))
            .addGroup(spindlePanelLayout.createSequentialGroup()
                .addGroup(spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spindlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(spindlePanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spindleResultLabel)
                            .addGroup(spindlePanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(spindlePanelLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(spindleMaterialBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(spindlePanelLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(diameterBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7)))))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        spindlePanelLayout.setVerticalGroup(
            spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spindlePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addGroup(spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spindlePanelLayout.createSequentialGroup()
                        .addGroup(spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spindleMaterialBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(spindlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(diameterBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(spindlePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spindleCalculateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(spindleResultLabel)
                .addGap(103, 103, 103))
        );

        jTabbedPane1.addTab("Spindle Speed (RPM)", spindlePanel);

        javax.swing.GroupLayout CNCPanelLayout = new javax.swing.GroupLayout(CNCPanel);
        CNCPanel.setLayout(CNCPanelLayout);
        CNCPanelLayout.setHorizontalGroup(
            CNCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        CNCPanelLayout.setVerticalGroup(
            CNCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CNCPanelLayout.createSequentialGroup()
                .addComponent(toolbarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );

        cardPanel.add(CNCPanel, "spindleCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Initalize
        resultLabel.setText("");
        
        //Create arrays
        int[] materials= {50,100,70,80,80,300,300,500,275};
        
        //Get material value 
        DefaultComboBoxModel materialListModel = (DefaultComboBoxModel) materialBox.getModel();
        drill.materialSpeed = materialListModel.getIndexOf(materialListModel.getSelectedItem());
        drill.materialSpeed = materials[drill.materialSpeed]; 
        
        //Get drill diamiter 
        drill.diameterString = (String)(diameterBox.getSelectedItem());
        
        //Finds diameter value and exicutes if no errors are found
        if (drill.findDiameter()==false){
            //Calculate
            drill.calculateRPM();
        
            //Output calculation result
            resultLabel.setText("= "+drill.RPM+" RPM");
        } else {
            resultLabel.setText(drill.errorMessage);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout)(cardPanel.getLayout());
        cl.show(cardPanel, "creditPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "RPMCard");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void feedRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedRateButtonActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "feedRateCard");
    }//GEN-LAST:event_feedRateButtonActionPerformed

    private void RPMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPMButtonActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "RPMCard");
    }//GEN-LAST:event_RPMButtonActionPerformed

    private void RPMMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPMMenuButtonActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "menuCard");
    }//GEN-LAST:event_RPMMenuButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "menuCard");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void creditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditButtonActionPerformed
        CardLayout cl = (CardLayout)(cardPanel.getLayout());
        cl.show(cardPanel, "creditPanel");
    }//GEN-LAST:event_creditButtonActionPerformed

    private void spindleSpeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spindleSpeedButtonActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "spindleCard");
    }//GEN-LAST:event_spindleSpeedButtonActionPerformed

    private void spindleMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spindleMenuButtonActionPerformed
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, "menuCard");
    }//GEN-LAST:event_spindleMenuButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout cl = (CardLayout)(cardPanel.getLayout());
        cl.show(cardPanel, "creditPanel");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void spindleCalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spindleCalculateButtonActionPerformed
        //Initalize
        spindleResultLabel.setText(" ");
        
        //Create arrays
        int[] spindleMaterials= {450,275,350,350,123,90,90};
        
        //Get material value 
        DefaultComboBoxModel materialListModel = (DefaultComboBoxModel) spindleMaterialBox.getModel();
        spindleDrill.materialSpeed = materialListModel.getIndexOf(materialListModel.getSelectedItem());
        spindleDrill.materialSpeed = spindleMaterials[spindleDrill.materialSpeed]; 
        
        //Get drill diamiter 
        spindleDrill.diameterString = (String)(diameterBox1.getSelectedItem());
        
        //Finds diameter value and exicutes if no errors are found
        if (spindleDrill.findDiameter()==false){
            //Calculate
            spindleDrill.calculateSpindle();
        
            //Output calculation result
            spindleResultLabel.setText("= "+spindleDrill.RPM+" RPM");
        } else {
            spindleResultLabel.setText(spindleDrill.errorMessage);
        }
    }//GEN-LAST:event_spindleCalculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuttingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuttingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuttingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuttingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuttingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CNCPanel;
    private javax.swing.JButton RPMButton;
    private javax.swing.JButton RPMMenuButton;
    private javax.swing.JPanel RPMPanel;
    private javax.swing.JLabel cameronDescription;
    private javax.swing.JLabel cameronLabel;
    private javax.swing.JSeparator cameronSeparator;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel cat;
    private javax.swing.JButton creditButton;
    private javax.swing.JPanel creditPanel;
    private javax.swing.JComboBox diameterBox;
    private javax.swing.JComboBox diameterBox1;
    private javax.swing.JButton feedRateButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel header;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jacobDescription;
    private javax.swing.JLabel jacobLabel;
    private javax.swing.JSeparator jacobSeparator;
    private javax.swing.JLabel kieranDescription;
    private javax.swing.JLabel kieranLabel;
    private javax.swing.JSeparator kieranSeparator;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JComboBox materialBox;
    private javax.swing.JLabel numeratorLabel;
    private javax.swing.JLabel ravenEyes;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel rpmLabel;
    private javax.swing.JButton spindleCalculateButton;
    private javax.swing.JComboBox spindleMaterialBox;
    private javax.swing.JButton spindleMenuButton;
    private javax.swing.JPanel spindlePanel;
    private javax.swing.JLabel spindleResultLabel;
    private javax.swing.JButton spindleSpeedButton;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JToolBar toolbar1;
    private javax.swing.JToolBar toolbar2;
    private javax.swing.JPanel toolbarPanel;
    private javax.swing.JPanel toolbarPanel1;
    // End of variables declaration//GEN-END:variables
}
